title          : "Dr. Semmelweis and the discovery of handwashing (R)"
description    : >
  Reanalyse the data behind one of the most important discoveries of modern medicine: Handwashing.
long_description: |
  In 1847 the Hungarian physician Ignaz Semmelweis makes a breakthough discovery: He discovers handwashing. Contaminated hands was a major cause of childbed fever and by enforcing handwashing at his hospital he saved hundreds of lives. 

  In this R project we will reanalyze the medical data Semmelweis collected. This project assumes you can manipulate data frames using `dplyr` and make simple plots using `ggplot2`. You can learn these skills in the course [Introduction to the Tidyverse](https://www.datacamp.com/courses/introduction-to-the-tidyverse).
language       : r
from           : 'r-notebooks-prod:36'
runtime_config : heavy
state          : live
technology: 1
instructors:
  - rasmus@datacamp.com
collaborators: []
prerequisites:
  - 4914
difficulty_level: 2
topics:
  - 3
  - 4
  - 12
time_needed: "60 minutes"
illustration: "https://s3.amazonaws.com/assets.datacamp.com/production/project_49/datasets/project_image.png"
